### ISSUE TITLE
Lets create an issue!!

### ISSUE THREAD

**Issue by johnklima** [ulvenpeter/sneakyguidance_Game#1]
bug/feature tracking is very useful in the course of development and all software companies use it. It is very important to get in the habit of reporting/opening issues, fixing, and closing them within the SCM (source control management) system and github includes this ability. So have a look the issues feature of github! Even if you are a small team, or solo, it is nice to remind yourself what the state of affairs is. Some familiarity will help you in a job interview!!

**Comment by johnklima** [comment]
lets see if someone notices this, and if so, make a comment and close the issue

**Comment by ulvenpeter** [comment]
We will have a look at it when we got The time for it
